#!/bin/bash

echo "<<< Start upgrade.lst updating >>>"

version="$(cat gradle.properties | grep '^version' | sed 's/version=\([0-9]*\)[.].*$/\1/g' )"
upgradle_log_path="db/src/main/resources/sql/work/updates/def/$version"
upgradle_log="$upgradle_log_path/db.def"
upgradle_txt="db/src/main/resources/sql/work/updates/upgrade.txt"

echo $(echo $upgradle_log | sed 's/\/.*%//g')

if [ ! -f $upgradle_log_path ]; then
    mkdir -p $upgradle_log_path
fi

if [ ! -f $upgradle_log ]; then
    echo -n > $upgradle_log
fi


# Имя текущей ветки
branch_name=$(git branch | grep "*" | sed "s/\* //")

# Имя ветки которая подливается в текущую
merged_branch=$(git reflog -1 | cut -d" " -f 4 | sed 's/://')

# Файл upgrade.lst
#upgradle_lst="db/src/main/resources/sql/work/updates/upgrade.lst"
if [ ! -z $upgradle_log ]; then
    echo "" >> $upgradle_log
fi

cat $upgradle_txt | sed '/^\s*$/d' >> $upgradle_log
echo -n > $upgradle_txt

git add *
git commit --all --amend --no-edit

echo "<<< Complete upgrade.lst updating >>>"